//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Malina_Nizametdinova
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities2 : DbContext
    {
        private static Entities2 _context;
        public Entities2()
            : base("name=Entities2")
        {
        }
        public static Entities2 GetContext()
        {
            if (_context == null)
                _context = new Entities2();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Employees> Employees { get; set; }
        public DbSet<Pavilions> Pavilions { get; set; }
        public DbSet<Rent> Rent { get; set; }
        public DbSet<SC> SC { get; set; }
        public DbSet<Tenants> Tenants { get; set; }
    }
}
