//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Malina_Nizametdinova
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pavilions
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string C__Pavilion { get; set; }
        public Nullable<int> Floor { get; set; }
        public string Status { get; set; }
        public Nullable<double> Area { get; set; }
        public Nullable<double> Cost_per_metr { get; set; }
        public Nullable<double> Value_added { get; set; }
    }
}
