//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Malina_Nizametdinova
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rent
    {
        public int ID { get; set; }
        public int ID_Tenant { get; set; }
        public string Name { get; set; }
        public int ID_Employee { get; set; }
        public string C__Pavilion { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Rent_start { get; set; }
        public Nullable<System.DateTime> Rent_end { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Tenants Tenants { get; set; }
    }
}
