//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Malina_Nizametdinova
{
    using System;
    using System.Collections.Generic;
    
    public partial class SC
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Status { get; set; }
        public Nullable<int> Pavilion_number { get; set; }
        public string City { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<double> Value_added { get; set; }
        public Nullable<int> Floors { get; set; }
        public string Image { get; set; }
    }
}
